# Generated by Django 5.0.7 on 2024-07-23 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cast', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField(max_length=500)),
                ('release_date', models.DateField()),
                ('movie_file', models.FileField(blank=True, null=True, upload_to='movies/%y-%m-%d')),
                ('thumbnail', models.FileField(upload_to='thumbnails/%y-%m-%d')),
                ('poster', models.FileField(upload_to='posters/%y-%m-%d')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='trailers/%y-%m-%d')),
                ('subtitle', models.FileField(blank=True, null=True, upload_to='subtitles/%y-%m-%d')),
                ('total_positive_votes', models.IntegerField(default=0, editable=False)),
                ('total_negative_votes', models.IntegerField(default=0, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cast_ids', models.ManyToManyField(related_name='movies', to='cast.cast', verbose_name='Casts')),
                ('genre_ids', models.ManyToManyField(to='movies.moviegenre', verbose_name='Genres')),
                ('tag_ids', models.ManyToManyField(to='movies.movietag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-release_date',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=255, null=True)),
                ('vote', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'unique_together': {('user_id', 'movie_id')},
            },
        ),
    ]
