# Generated by Django 4.1.5 on 2023-08-31 10:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_file_movie_thumbnail_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(default=23, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(upload_to=''),
        ),
    ]
