# Generated by Django 4.1.5 on 2023-08-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_movie_file_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subtitle',
            field=models.FileField(default=3242, upload_to='subtitles/%y-%m-%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(upload_to='movies/%y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(upload_to='thumbnails/%y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(upload_to='trailers/%y-%m-%d'),
        ),
    ]
