# Generated by Django 4.1.5 on 2023-08-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_moviegenre_movietag_movie_genre_ids_movie_tag_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre_ids',
            field=models.ManyToManyField(to='movies.moviegenre', verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tag_ids',
            field=models.ManyToManyField(to='movies.movietag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movietag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
