# Generated by Django 4.1.5 on 2023-09-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0001_initial'),
        ('movies', '0006_alter_movie_genre_ids_alter_movie_tag_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast_ids',
            field=models.ManyToManyField(to='cast.cast', verbose_name='Casts'),
        ),
    ]
