# Generated by Django 4.1.5 on 2023-09-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0001_initial'),
        ('movies', '0007_movie_cast_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast_ids',
            field=models.ManyToManyField(related_name='movies', to='cast.cast', verbose_name='Casts'),
        ),
    ]
