# Generated by Django 4.1.5 on 2023-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_positive_votes_percentage',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_reviews',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
