# Generated by Django 4.1.5 on 2023-09-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_total_positive_votes_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='total_positive_votes_percentage',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='total_reviews',
        ),
    ]
