# Generated by Django 4.1.5 on 2023-09-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_review_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_negative_votes',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='total_positive_votes',
            field=models.IntegerField(default=12, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(blank=True, null=True, upload_to='movies/%y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='subtitle',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/%y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailers/%y-%m-%d'),
        ),
    ]
