# Generated by Django 4.1.5 on 2023-09-21 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_poster_movie_total_negative_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 21, 7, 48, 52, 663300, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        )
    ]
