# Generated by Django 4.1.5 on 2023-09-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_created_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='total_negative_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='total_positive_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
