# Generated by Django 4.1.5 on 2023-09-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movie_poster_alter_movie_total_negative_votes_and_more'),
    ]

    operations = [
    ]
