# Generated by Django 4.1.5 on 2023-09-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_movie_poster'),
    ]

    operations = [
    ]
