# Generated by Django 4.1.5 on 2023-09-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.FileField(default=1, upload_to='posters/%y-%m-%d'),
            preserve_default=False,
        ),
    ]
