# Generated by Django 4.1.5 on 2023-10-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_movie_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-release_date',)},
        ),
    ]
