# Generated by Django 4.1.5 on 2023-10-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_movie_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='total_negative_votes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='total_positive_votes',
        ),
    ]
