# Generated by Django 4.1.5 on 2023-10-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_remove_movie_total_negative_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_negative_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_positive_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
