# Generated by Django 4.1.5 on 2023-09-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(upload_to='cast_images')),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
