# Generated by Django 5.0.7 on 2024-07-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=255)),
                ('picture', models.ImageField(upload_to='cast_images')),
                ('date_of_birth', models.DateField()),
                ('full_bio', models.TextField(max_length=2000)),
                ('birth_place', models.CharField(max_length=120)),
                ('birth_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('quote', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CastImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cast_extra_images')),
                ('cast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cast.cast')),
            ],
        ),
    ]
